# Generated by Django 2.0.2 on 2018-04-15 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.IntegerField(blank=True, null=True)),
                ('info', models.CharField(blank=True, max_length=7, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('taskList', models.CharField(blank=True, max_length=9000, null=True)),
                ('mistakeList', models.CharField(blank=True, max_length=9000, null=True)),
                ('lastTask', models.CharField(blank=True, max_length=100, null=True)),
                ('startTime', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Время начала эксперимента')),
                ('timing', models.FloatField(blank=True, default=1.6421844337337525e-05, null=True, verbose_name='Время затраченное на эксперимент')),
                ('replay', models.BooleanField()),
                ('mistake', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True, null=True)),
                ('quest', models.CharField(blank=True, max_length=6, null=True, verbose_name='Задание')),
                ('answer', models.CharField(blank=True, max_length=6, null=True, verbose_name='Правильный ответ')),
                ('checking', models.CharField(blank=True, default='Не счастливый', max_length=100, null=True)),
                ('startTime', models.FloatField(blank=True, default=0.2042639318821897, null=True, verbose_name='Время попадания на страницу')),
                ('task_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='Ваш Ответ ')),
                ('check', models.CharField(blank=True, default='Не счастливый', max_length=100, null=True)),
                ('answerTime', models.FloatField(blank=True, default=0.20491013145686393, null=True, verbose_name='Время ответа')),
                ('time', models.FloatField(blank=True, default=0.20492367947844223, null=True, verbose_name='Затраченное время')),
                ('variant_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
            ],
        ),
    ]
