# Generated by Django 2.0.2 on 2018-03-03 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(max_length=1)),
                ('lev_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.IntegerField(max_length=6)),
                ('answer', models.IntegerField(max_length=6)),
                ('variant', models.IntegerField(max_length=6)),
                ('task_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Level')),
            ],
        ),
    ]
