# Generated by Django 2.0.2 on 2018-03-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_experiment_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='user_name',
            new_name='name',
        ),
    ]
