# Generated by Django 2.0.2 on 2018-03-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20180307_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='variant',
            field=models.CharField(max_length=6, verbose_name='Ваш Ответ '),
        ),
    ]
