# Generated by Django 2.0.2 on 2018-03-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20180309_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='variant',
            field=models.CharField(default='Пусто', max_length=6, verbose_name='Ваш Ответ '),
        ),
    ]
