# Generated by Django 2.0.2 on 2018-03-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20180310_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='checking',
            field=models.CharField(default='Не решено', max_length=9),
        ),
        migrations.AddField(
            model_name='task',
            name='startTime',
            field=models.IntegerField(default=0, verbose_name='Время попадания на страницу'),
        ),
        migrations.AddField(
            model_name='variant',
            name='answerTime',
            field=models.IntegerField(default=0, verbose_name='Время ответа'),
        ),
        migrations.AddField(
            model_name='variant',
            name='time',
            field=models.IntegerField(default=0, verbose_name='Затраченное время'),
        ),
        migrations.AlterField(
            model_name='task',
            name='answer',
            field=models.CharField(max_length=6, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='quest',
            field=models.CharField(max_length=6, verbose_name='Задание'),
        ),
    ]
