# Generated by Django 2.0.2 on 2018-03-11 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20180311_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='startTime',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Время попадания на страницу'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='answerTime',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Время ответа'),
        ),
    ]
