# Generated by Django 2.0.2 on 2018-03-11 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20180311_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Затраченное время'),
        ),
    ]
