# Generated by Django 2.0.2 on 2018-03-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20180311_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='startTime',
            field=models.FloatField(default=4.105464455299292e-07, verbose_name='Время попадания на страницу'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='answerTime',
            field=models.FloatField(default=0.0004906030024082655, verbose_name='Время ответа'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='time',
            field=models.FloatField(default=0.0005025088493286334, verbose_name='Затраченное время'),
        ),
    ]
