# Generated by Django 2.0.2 on 2018-03-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_auto_20180315_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='taskList',
            field=models.CharField(default='', max_length=9000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variant',
            name='answerTime',
            field=models.FloatField(default=0.0004942981233503723, verbose_name='Время ответа'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='time',
            field=models.FloatField(default=0.0005057934285445671, verbose_name='Затраченное время'),
        ),
    ]
