# Generated by Django 2.0.2 on 2018-03-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_auto_20180315_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='info',
            field=models.CharField(default='Открыто', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='startTime',
            field=models.FloatField(default=0.0, verbose_name='Время попадания на страницу'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='answerTime',
            field=models.FloatField(default=0.0008477787580718596, verbose_name='Время ответа'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='time',
            field=models.FloatField(default=0.0008695377286180139, verbose_name='Затраченное время'),
        ),
    ]
