# Generated by Django 2.0.2 on 2018-03-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_auto_20180317_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='checking',
            field=models.CharField(default='Не решено', max_length=100),
        ),
        migrations.AlterField(
            model_name='variant',
            name='answerTime',
            field=models.FloatField(default=0.000502919808718043, verbose_name='Время ответа'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='check',
            field=models.CharField(default='Не решено', max_length=100),
        ),
        migrations.AlterField(
            model_name='variant',
            name='time',
            field=models.FloatField(default=0.0005152362121968523, verbose_name='Затраченное время'),
        ),
    ]
