# Generated by Django 2.0.2 on 2018-03-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_auto_20180322_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='mistakeList',
            field=models.CharField(default='', max_length=9000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='startTime',
            field=models.FloatField(default=4.105466140783824e-07, verbose_name='Время попадания на страницу'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='answerTime',
            field=models.FloatField(default=0.0008880123262515411, verbose_name='Время ответа'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='time',
            field=models.FloatField(default=0.0009097712967976953, verbose_name='Затраченное время'),
        ),
    ]
