# Generated by Django 2.0.2 on 2018-03-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_auto_20180324_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='mistake',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='replay',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variant',
            name='answerTime',
            field=models.FloatField(default=0.0005419215305834648, verbose_name='Время ответа'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='time',
            field=models.FloatField(default=0.0006330628789088656, verbose_name='Затраченное время'),
        ),
    ]
