# Generated by Django 2.0.2 on 2018-03-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_auto_20180324_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='lastTask',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='startTime',
            field=models.FloatField(default=4.105467826269739e-07, verbose_name='Время попадания на страницу'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='answerTime',
            field=models.FloatField(default=0.0007278994455976247, verbose_name='Время ответа'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='time',
            field=models.FloatField(default=0.0008765173809085893, verbose_name='Затраченное время'),
        ),
    ]
