# Generated by Django 2.0.2 on 2018-04-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_auto_20180331_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='Time',
            field=models.FloatField(default=8.046716939488688e-05, verbose_name='Время затраченное на эксперимент'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='startTime',
            field=models.FloatField(default=8.210935652539478e-07, verbose_name='Время начала эксперимента'),
        ),
        migrations.AlterField(
            model_name='task',
            name='checking',
            field=models.CharField(default='Не счастливый', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='startTime',
            field=models.FloatField(default=1.2554594511153736, verbose_name='Время попадания на страницу'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='answerTime',
            field=models.FloatField(default=1.2560342166110512, verbose_name='Время ответа'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='check',
            field=models.CharField(default='Не счастливый', max_length=100),
        ),
        migrations.AlterField(
            model_name='variant',
            name='time',
            field=models.FloatField(default=1.25604653301453, verbose_name='Затраченное время'),
        ),
    ]
